#!/usr/bin/env python3
"""LACES_CASES data butler — automated end-of-day cleanup + next-day prep.

Usage:
  python .state/butler.py               # EOD run (default)
  python .state/butler.py --eod         # same as default
  python .state/butler.py --watch       # poll state.json, regen dash on change
  python .state/butler.py --watch --watch-interval 30

The butler NEVER edits state.json sessions/tasks — it only READS state and WRITES
archive artifacts + the dashboard. Agent-written entries stay authoritative; the
activity scan is clearly labeled as machine-detected.

Outputs (all inside .state/):
  archive/YYYY-MM-DD_state.json   snapshot of state.json
  archive/YYYY-MM-DD_brief.md     the day brief (also copied to LATEST_BRIEF.md)
  dash.html                       regenerated dashboard
  butler.log                      append-only run log
"""
import argparse
import json
import os
import sys
import time
from datetime import date, datetime

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)  # workspace root
STATE_PATH = os.path.join(HERE, "state.json")
ARCHIVE_DIR = os.path.join(HERE, "archive")
BRIEF_LATEST = os.path.join(HERE, "LATEST_BRIEF.md")
LOG_PATH = os.path.join(HERE, "butler.log")
RECEIPTS = os.path.join(ROOT, "dotmd", ".ijfw", "receipts", "cross-runs.jsonl")

SKIP_DIRS = {
    ".git", ".freebuff", ".state", ".ijfw", "__pycache__",
    "node_modules", ".planning", "venv", ".venv", "dist", "build",
}


def log(msg):
    line = f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] {msg}"
    try:
        with open(LOG_PATH, "a", encoding="utf-8") as f:
            f.write(line + "\n")
    except OSError:
        pass
    print(line)


def detect_changes(since):
    """Files modified since `since`, newest first, capped at 50, relative to root."""
    changed = []
    for base in (ROOT,):
        if not os.path.isdir(base):
            continue
        for dirpath, dirnames, filenames in os.walk(base):
            dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
            for fn in filenames:
                if fn.endswith((".pyc", ".log")) or fn in ("dash.html",):
                    continue
                p = os.path.join(dirpath, fn)
                try:
                    mt = datetime.fromtimestamp(os.path.getmtime(p))
                except OSError:
                    continue
                if mt >= since:
                    rel = os.path.relpath(p, ROOT)
                    if rel.startswith("dotmd" + os.sep + ".ijfw"):
                        continue
                    changed.append((mt, rel))
    changed.sort(reverse=True)
    return changed[:50]


def recent_audits():
    """Summarize today's ijfw audit receipts (fields only — never the target blob)."""
    entries = []
    if not os.path.isfile(RECEIPTS):
        return entries
    try:
        with open(RECEIPTS, encoding="utf-8") as f:
            lines = f.readlines()
    except OSError:
        return entries
    today = date.today().isoformat()
    for line in lines[-6:]:
        try:
            d = json.loads(line)
        except Exception:
            continue
        ts = str(d.get("timestamp", ""))
        if ts[:10] != today:
            continue
        auditors = d.get("auditors", [])
        ok = [a.get("id") for a in auditors if a.get("status") == "ok"]
        failed = [a.get("id") for a in auditors if a.get("status") == "failed"]
        findings = len((d.get("findings") or {}).get("items", []))
        target = str(d.get("target", "")).replace("\n", " ")[:80]
        entries.append({
            "time": ts[11:19],
            "mode": d.get("mode", "?"),
            "target": target,
            "ok": ok,
            "failed": failed,
            "findings": findings,
            "duration_s": round((d.get("duration_ms") or 0) / 1000.0, 1),
        })
    return entries


def write_brief(st, changes, audits, day):
    open_sessions = [s for s in st.get("sessions", []) if s.get("status") == "open"]
    tasks = [t for t in st.get("tasks", []) if t.get("status") not in ("done", "cancelled")]
    goals = st.get("goals", {})

    L = []
    L.append(f"# Day Brief — {day}")
    L.append(f"*Auto-generated by the data butler at {datetime.now().strftime('%H:%M')}. "
             "Session content is agent-authored; the activity scan is machine-detected.*")
    L.append("")
    L.append("## Overall goal")
    L.append(goals.get("overall", ""))
    L.append("")
    L.append("## Today's goal")
    L.append(goals.get("today", ""))
    L.append("")

    L.append(f"## Open sessions ({len(open_sessions)})")
    for s in open_sessions:
        L.append(f"### {s.get('task')}  [{s.get('id')}]")
        L.append(f"- tab: {s.get('tab')} | agent: {s.get('agent')} | last update: {s.get('last_update')}")
        for a in s.get("accomplished", []):
            L.append(f"  - done: {a}")
        for n in s.get("next_steps", []):
            L.append(f"  - next: {n}")
        L.append("")

    L.append(f"## Open tasks ({len(tasks)})")
    for t in tasks:
        L.append(f"- [{t.get('status')}] ({t.get('priority')}) {t.get('title')} — {t.get('notes', '')}")
    L.append("")

    L.append(f"## Detected activity today ({len(changes)} files touched)")
    if changes:
        for mt, rel in changes:
            L.append(f"- {mt.strftime('%H:%M')}  {rel}")
    else:
        L.append("- none detected")
    L.append("")

    L.append(f"## Audits run today ({len(audits)})")
    if audits:
        for a in audits:
            L.append(f"- {a['time']} {a['mode']} on {a['target']} — "
                     f"{len(a['ok'])} ok / {len(a['failed'])} failed, {a['findings']} findings, {a['duration_s']}s")
    else:
        L.append("- none detected")
    L.append("")

    L.append("## Resume plan for next session")
    seen = set()
    for s in open_sessions:
        for n in s.get("next_steps", []):
            if n not in seen:
                L.append(f"- [ ] {n}")
                seen.add(n)
    L.append("")

    body = "\n".join(L)
    with open(os.path.join(ARCHIVE_DIR, f"{day}_brief.md"), "w", encoding="utf-8") as f:
        f.write(body)
    with open(BRIEF_LATEST, "w", encoding="utf-8") as f:
        f.write(body)
    return body


def snapshot_state(st, day):
    path = os.path.join(ARCHIVE_DIR, f"{day}_state.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(st, f, indent=2, ensure_ascii=False)
    return path


def run_eod():
    os.makedirs(ARCHIVE_DIR, exist_ok=True)
    if not os.path.isfile(STATE_PATH):
        log("ERROR: state.json missing; nothing to do")
        return 1
    with open(STATE_PATH, encoding="utf-8") as f:
        st = json.load(f)

    today = date.today().isoformat()
    since = datetime.combine(date.today(), datetime.min.time())
    changes = detect_changes(since)
    audits = recent_audits()
    body = write_brief(st, changes, audits, today)
    snap = snapshot_state(st, today)

    try:
        sys.path.insert(0, HERE)
        import gen_dash
        gen_dash.main()
    except Exception as e:
        log(f"WARN: dashboard regen failed: {e}")

    try:
        import gen_projects_dash
        if os.path.isdir(gen_projects_dash.LEDGER):
            gen_projects_dash.main()
            log("projects board regenerated")
        else:
            log("projects board skipped: ledger not present")
    except Exception as e:
        log(f"WARN: projects board regen failed: {e}")

    try:
        sys.path.insert(0, os.path.join(HERE, "kiss"))
        import gen_kiss
        gen_kiss.main()
        log("kiss deck regenerated")
    except Exception as e:
        log(f"WARN: kiss deck regen failed: {e}")

    log(f"EOD butler done: brief={len(body)} chars | snapshot={os.path.basename(snap)} | "
        f"{len(changes)} files touched today | {len(audits)} audits today")
    return 0


def run_watch(interval):
    log(f"butler --watch started (interval {interval}s) — regenerating dash.html whenever state.json changes")
    last_mtime = None
    try:
        last_mtime = os.path.getmtime(STATE_PATH)
    except OSError:
        pass
    while True:
        time.sleep(interval)
        try:
            mt = os.path.getmtime(STATE_PATH)
        except OSError:
            continue
        if mt != last_mtime:
            last_mtime = mt
            try:
                sys.path.insert(0, HERE)
                import gen_dash
                gen_dash.main()
                log("dash regenerated (state.json changed)")
            except Exception as e:
                log(f"WARN: dashboard regen failed: {e}")


def main():
    ap = argparse.ArgumentParser(description="LACES_CASES data butler")
    ap.add_argument("--eod", action="store_true", help="end-of-day run (this is the default)")
    ap.add_argument("--watch", action="store_true", help="watch state.json and regen the dash on change")
    ap.add_argument("--watch-interval", type=int, default=60, help="watch poll interval in seconds")
    args = ap.parse_args()
    if args.watch:
        run_watch(args.watch_interval)
    else:
        return run_eod()


if __name__ == "__main__":
    sys.exit(main())
